//
// Created by oxymmiron on 13.07.2024.
//

#ifndef RISCURELIBCPP_RISCUREPOWERTRACERCONSTANTS_H
#define RISCURELIBCPP_RISCUREPOWERTRACERCONSTANTS_H

#endif //RISCURELIBCPP_RISCUREPOWERTRACERCONSTANTS_H
