//
// Created by oxymmiron on 13.07.2024.
//

#ifndef RISCURELIBCPP_RISCUREPOWERTRACERINTEFACES_H
#define RISCURELIBCPP_RISCUREPOWERTRACERINTEFACES_H

 class IPowerTracer{

};


#endif //RISCURELIBCPP_RISCUREPOWERTRACERINTEFACES_H
